#!/bin/sh

# Organic.el — command line interface for Emacs Org-mode.
# Copyright © 2020 Ivan Gankevich
# 
# This file is part of Organic.el.
# 
# Organic.el is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Organic.el is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Organic.el.  If not, see <https://www.gnu.org/licenses/>.

exec emacs --batch --quick --load=$(dirname $0)/organic.el -- "$@"
